### ISSUE TITLE
Modifications and Bugs 

### ISSUE THREAD

**Issue by iRhonin** [SAY-DAO/frontend#4]
# General
- [x] Styles don't work on desktop 
![image](https://user-images.githubusercontent.com/13151232/140740432-ed341665-3797-42c6-9b7e-6866e72fe1c3.png)

- [x] #5
![image](https://user-images.githubusercontent.com/13151232/140740618-419e4bea-18f8-4b89-8d20-dcfb9f2606ad.png)
![image](https://user-images.githubusercontent.com/13151232/140741342-5a31d204-c9bf-467b-a66e-da59800e3cbf.png)
![image](https://user-images.githubusercontent.com/13151232/140742053-0b393fe1-59c7-4f63-8b03-04b30f2be1d8.png)
![image](https://user-images.githubusercontent.com/13151232/140742371-a6c5a0d9-5b14-4901-b841-37077f2860bc.png)
![image](https://user-images.githubusercontent.com/13151232/140742448-bd508e79-5b15-4739-b506-b2935ee1f695.png)
![image](https://user-images.githubusercontent.com/13151232/140742748-a7321040-548d-43d8-a9be-8302ecabc024.png)
![image](https://user-images.githubusercontent.com/13151232/140742806-361b50c6-f3f2-4820-86aa-cb3d2f4d8c30.png)
![image](https://user-images.githubusercontent.com/13151232/140744059-2dfdd939-d344-44f0-8e89-ab7cc8148299.png)

- [x] Border on all popups
![image](https://user-images.githubusercontent.com/13151232/140741590-852640e7-0cc1-440d-82fe-e89cd57e57e3.png)

- [x] Options on (all)popups are same color
![image](https://user-images.githubusercontent.com/13151232/140741653-bc5bcd47-172f-4b62-a0b9-e682927e919d.png)

- [x] Texts need more `line height`
![image](https://user-images.githubusercontent.com/59148169/140813671-d78b7668-7db9-4b59-a77f-69da5a17043b.png)

# Splash page
- [x] Logo and app name on splash page
![image](https://user-images.githubusercontent.com/59148169/140812813-ca56687f-0ba8-4e37-8b3b-b9ecf2aad216.png)

# Register
- [x] Register page does not go next step
![image](https://user-images.githubusercontent.com/13151232/140741166-dbe1400b-0660-4bdd-abaa-a34db524d6b2.png)

# Reset password
- [x] Reset password confirmation page redirect to login page
![image](https://user-images.githubusercontent.com/13151232/140740892-a70fe245-c99e-458e-8bff-ec88313439d3.png)

# Dashboard
- [x] payments info on child card needs `align center`
![image](https://user-images.githubusercontent.com/59148169/140813799-7a70efaa-58ab-48eb-b1df-384f5af21eef.png)

- [x]  Background username overlaps the profile image (on both dashboard and profile page)
![image](https://user-images.githubusercontent.com/59148169/140813928-d23b0f52-69ad-46c3-bc55-ec2307ac9a1d.png)

# Profile page
- [x] Profile missing some fields
![image](https://user-images.githubusercontent.com/13151232/140741964-ad0f31e3-f391-40b8-baac-f718f369a4ab.png)

# Child page
- [x] Font bug on child living town weather 
![image](https://user-images.githubusercontent.com/13151232/140742194-36849826-50d3-4bd5-97ed-37040949f518.png)

- [x] Weather info goes out of header on my phone
![image](https://user-images.githubusercontent.com/59148169/140813976-0e82fb8c-16c5-401a-8f17-c6653f9d797f.png)

- [x] Category icons are larger than their box
![image](https://user-images.githubusercontent.com/13151232/140742285-be8b109c-3f08-4c9e-9617-136df1440f8c.png)

# Need page
- [x] Missing participation amount in when need is done
![image](https://user-images.githubusercontent.com/13151232/140742537-6352f59f-8e9d-4c67-a1a1-2cbad14b101b.png)

- [x] Null participant on one of done needs
![image](https://user-images.githubusercontent.com/59148169/140814014-2de1d97a-db27-4e79-9bc0-4bb1654b4d90.png)

- [x] Width of need meta data is not 100% 
![image](https://user-images.githubusercontent.com/13151232/140742673-db8ffa6b-57ff-46b4-ba82-aac31b03e94b.png)

- [x] Credit checkbox not working
![image](https://user-images.githubusercontent.com/13151232/140742869-22f48818-0d72-4790-9b51-c9bf3b9c3476.png)

- [x] Support the path popup dupplicate the componet
![image](https://user-images.githubusercontent.com/13151232/140743003-530f34c0-7408-42d4-a4cf-0e8b079b5b54.png)

- [x] Infinite refresh on need page when tap pay button, (it should refresh only when need data changed) and keep opening idpay page on each refresh
![image](https://user-images.githubusercontent.com/13151232/140743674-f94e0d77-6ac7-4e96-8a0c-c25823e68467.png)

- [x] Payment button should be disabled when clicked to prevent multiple click also feels its it stucked

- [x] Refresh on need/child page redirects user to home

- [x] Pay btn text color remain disable when I choose unavailable Pay some amount, then switch to Pay all or Add to cart 
![image](https://user-images.githubusercontent.com/59148169/140814093-0d387200-13ea-49d9-a501-ba91bdc561f1.png)

# Cart page
- [x] Donation options are zero on cart page
![image](https://user-images.githubusercontent.com/59148169/140814172-9ccad663-9fae-4279-92f0-45e6f6e966c0.png)

# Search result page
- [ ] It shows a new random child on browser back button

- [ ] It redirects to `search page` on refresh

# Settings page
- [x] Item icons need some margin from the edge
![image](https://user-images.githubusercontent.com/59148169/140814251-e2d4afe9-6415-4b5c-bedb-bd55f6d574a3.png)

**Comment by ehsan-g** [comment]
@iRhonin on which browser are you seeing the dialogues borders?

**Comment by iRhonin** [comment]
> @iRhonin on which browser are you seeing the dialogues borders?

On Brave.

**Comment by ehsan-g** [comment]
> > @iRhonin on which browser are you seeing the dialogues borders?
> 
> On Brave.

**Comment by ehsan-g** [comment]
> > @iRhonin on which browser are you seeing the dialogues borders?
> 
> On Brave.
- Brave was okay on my end
-  did not see this one as well ' It shows a new random child on browser back button'

**Comment by iRhonin** [comment]
> > > @iRhonin on which browser are you seeing the dialogues borders?
> > 
> > 
> > On Brave.
> 
> * Brave was okay on my end
> * did not see this one as well ' It shows a new random child on browser back button'

@ehsan-g first issue still exists for me, and as soon as I open inspect element, it fades.
@Elhamne Can you please check if the second issue still exists?

**Comment by Elhamne** [comment]
@iRhonin  It takes me so long to open random search result, it remains on loading circle. 
And when I refresh that, it shows NaN child.
I'm checking at [s.sayapp.company](https://s.sayapp.company)
<hr>

### UPDATE
NaN child and random child opening is fixed for me.
But now on browser back button click, it remains on loading circle.
@ehsan-g

**Comment by iRhonin** [comment]
@ehsan-g I found these:

- [x] Cart gets deleted if the user logs out and logged back in.
- [x] Bottom menu disappeared on any page except the main pages (Child/Need,... page)
- [x] Credit check button is off by default
- [x] Credit amount is incorrect in the Need/Cart pages, shows 0 when disabled and wrong amount when enabled 
![image](https://user-images.githubusercontent.com/13151232/142769808-ce212f5c-e9ca-48ac-9053-fd04d52a5a5c.png)
![image](https://user-images.githubusercontent.com/13151232/142769817-edccc7ea-aa50-4def-a2d7-264e27dec31b.png)

- [x] Unmatched boxes (borders) on the Cart page 
![image](https://user-images.githubusercontent.com/13151232/142769768-8a5ac0b0-553a-4611-8372-3dd6b3ac5322.png)

**Comment by iRhonin** [comment]
- [x] Username length error should be 6 to 16 instead of 8 to 16

![image](https://user-images.githubusercontent.com/13151232/142775135-1726b02b-3f7b-4c60-a8ec-f95104f46b79.png)

**Comment by Elhamne** [comment]
@ehsan-g 
- [x] Favicon logo shoud be replace 
![image](https://user-images.githubusercontent.com/59148169/143205237-ed91a6bb-e730-4ad7-a524-c89dd1b3cd88.png)

- [x] There is no Back button on NeedPage and ChildPage
**Update**
There is Back button on Need and Child Page, but it's not visible on desktop cause it's white.
![image](https://user-images.githubusercontent.com/59148169/143218168-50223f63-7cfe-460b-91ae-1a07b9ae4ddf.png)
 
- [ ] Pay some amount cannot be deleted fully to type custom amount (0 remain at the end), unless u select all.
![image](https://user-images.githubusercontent.com/59148169/143489296-3af522c3-4fce-4dd8-928e-21163ca5929c.png)

**Comment by Elhamne** [comment]
@ehsan-g 

- [x] On gone child page, after I close the popup sth is still on screen that doesn't let me click on anything in the page! It only happened on chrome and brave I've tested but it's OK on firefox. This element: 
![image](https://user-images.githubusercontent.com/59148169/144204217-f9c861d3-ce17-4a08-8fe5-85da9c10b49b.png)

- [x] Status and SAY logo on report pages:
![image](https://user-images.githubusercontent.com/59148169/144204475-5cb171d7-3d3b-41ff-9ffa-ea00d4716f31.png)

- [ ] The stepper line on Done need pages is out of the box on ENG version:
![image](https://user-images.githubusercontent.com/59148169/144204823-5739cdb5-d1f8-4f82-bf7d-01413447aae0.png)

**Comment by ehsan-g** [comment]
> * [ ]  Username length error should be 6 to 16 instead of 8 to 16
> 
> 
> ![image](https://user-images.githubusercontent.com/13151232/142775135-1726b02b-3f7b-4c60-a8ec-f95104f46b79.png)
-----------------------------------------------
@iRhonin 
The problem is those who already registered usernames with less than 6 characters will not be able to log in.

Also Which one is this:
 **Bottom menu disappeared on any page except the main pages (Child/Need,... page)**

**Comment by ehsan-g** [comment]
@iRhonin **https://sayapp.company/public/resources/img/ngo_delivered.jpg** is causing the issue Elham has mentioned above. I think you need to fix this from your end.

**Comment by iRhonin** [comment]
> @iRhonin **https://sayapp.company/public/resources/img/ngo_delivered.jpg** is causing the issue Elham has mentioned above. I think you need to fix this from your end.

I will patch a temporary fix for that, but the frontend should serve this image (and similar images) locally.

**Comment by iRhonin** [comment]
@ehsan-g, By the bottom menu I mean: 
![image](https://user-images.githubusercontent.com/13151232/144674862-c23ba4ff-ab1e-48f4-ba42-f525563915c2.png)

**Comment by iRhonin** [comment]
> > * [ ]   Username length error should be 6 to 16 instead of 8 to 16
> > 
> > ![image](https://user-images.githubusercontent.com/13151232/142775135-1726b02b-3f7b-4c60-a8ec-f95104f46b79.png)
> 
> @iRhonin The problem is those who already registered usernames with less than 6 characters will not be able to log in.

I can not see how this will affect less than 6 characters usernames? Can you please explain more? @ehsan-g

**Comment by ehsan-g** [comment]
> > > * [ ]    Username length error should be 6 to 16 instead of 8 to 16
> > > 
> > > ![image](https://user-images.githubusercontent.com/13151232/142775135-1726b02b-3f7b-4c60-a8ec-f95104f46b79.png)
> > 
> > 
> > @iRhonin The problem is those who already registered usernames with less than 6 characters will not be able to log in.
> 
> I can not see how this will affect less than 6 characters usernames? Can you please explain more? @ehsan-g

We use the same validation when logging in, and those with 6 char will not be able to sign in

**Comment by ehsan-g** [comment]
> > @iRhonin **https://sayapp.company/public/resources/img/ngo_delivered.jpg** is causing the issue Elham has mentioned above. I think you need to fix this from your end.
> 
> I will patch a temporary fix for that, but the frontend should serve this image (and similar images) locally.

it should, but you are already sending some assets like logo for participants. we should fix the whole thing.

**Comment by ehsan-g** [comment]
> @ehsan-g, By the bottom menu I mean: ![image](https://user-images.githubusercontent.com/13151232/144674862-c23ba4ff-ab1e-48f4-ba42-f525563915c2.png)

infinite scrolling is more desirable in UI/UX, and to separate / emphasis on the main concept and other pages we need to do this. This also creates more flexibility in regard to adding new features on need and child page in future.

**Comment by iRhonin** [comment]
> We use the same validation when logging in, and those with 6 char will not be able to sign in

There is no username validation on the login page of the beta app last time I checked.
Besides that, **current** limit on the beta app is 8, not 6, so I think we should lower that to 6.

---
> it should, but you are already sending some assets like logo for participants. we should fix the whole thing.

In the last update (with the lunch of the beta), we changed all assets (like avatars, need's image, ...) to be a full path URL (like https://api.sayapp.company/files/...), and replaced remote assets in the web app (like fonts, logo, need status updated icons, ...) to be a static file inside the app.

If you find any assets that are not fixed it is a bug and please report them to get fixed.

For now, we are using Cloudflare redirect rule to redirect `sayapp.company/public/*` to `api.sayapp.company/public/*`, the problem with this patch is we are on the limit of available rules of CloudFlare, so fixing this issue is pretty urgent. 

---

> infinite scrolling is more desirable in UI/UX, and to separate / emphasis on the main concept and other pages we need to do this. This also creates more flexibility in regard to adding new features on need and child page in future.

I completely agree with having infinite scrolling, especially on the `done category of child page`.
But I think they serve different purposes, having the navigation bar (the footer menu) on every (or some important) page can help navigation between pages significantly, for example, navigating from the need page to the cart/dashboard is a 2-step action and not very straightforward/clean and navigation bar can improve this experience.

@ehsan-g

**Comment by Elhamne** [comment]
- [x] Cannot switch to the **URGENT** category on child's page:
![image](https://user-images.githubusercontent.com/59148169/147810607-6983b374-3d71-43e6-a224-89e927387f1f.png)

@ehsan-g

**Comment by ehsan-g** [comment]
> > We use the same validation when logging in, and those with 6 char will not be able to sign in
> 
> There is no username validation on the login page of the beta app last time I checked. Besides that, **current** limit on the beta app is 8, not 6, so I think we should lower that to 6.
> 
> > it should, but you are already sending some assets like logo for participants. we should fix the whole thing.
> 
> In the last update (with the lunch of the beta), we changed all assets (like avatars, need's image, ...) to be a full path URL (like https://api.sayapp.company/files/...), and replaced remote assets in the web app (like fonts, logo, need status updated icons, ...) to be a static file inside the app.
> 
> If you find any assets that are not fixed it is a bug and please report them to get fixed.
> 
> For now, we are using Cloudflare redirect rule to redirect `sayapp.company/public/*` to `api.sayapp.company/public/*`, the problem with this patch is we are on the limit of available rules of CloudFlare, so fixing this issue is pretty urgent.
> 
> > infinite scrolling is more desirable in UI/UX, and to separate / emphasis on the main concept and other pages we need to do this. This also creates more flexibility in regard to adding new features on need and child page in future.
> 
> I completely agree with having infinite scrolling, especially on the `done category of child page`. But I think they serve different purposes, having the navigation bar (the footer menu) on every (or some important) page can help navigation between pages significantly, for example, navigating from the need page to the cart/dashboard is a 2-step action and not very straightforward/clean and navigation bar can improve this experience.
> 
@iRhonin 
![username err](https://user-images.githubusercontent.com/60781475/147833411-3671758c-e73a-4fd0-b663-9c1dbb819b52.png)


The page I was referring is the profile edit, where users want to edit their username

**Comment by ehsan-g** [comment]
@iRhonin this is the link you are sending: 
https://api.s.sayapp.company/public/resources/img/logo.png
https://api.s.sayapp.company/public/resources/img/logo.png
but my resources are not at this link

**Comment by ehsan-g** [comment]
@iRhonin regarding the infinite scrolling: I think the Go To Cart Button does the trick just like the appbar.

**Comment by iRhonin** [comment]
> The page I was referring is the profile edit, where users want to edit their username

I will call you to discuss this in the next week if it is ok with you.

> @iRhonin regarding the infinite scrolling: I think the Go To Cart Button does the trick just like the appbar.

So we need to agree to disagree 🤷‍♂️.

**Comment by ehsan-g** [comment]
> > The page I was referring is the profile edit, where users want to edit their username
> 
> I will call you to discuss this in the next week if it is ok with you.
> 
> > @iRhonin regarding the infinite scrolling: I think the Go To Cart Button does the trick just like the appbar.
> 
> So we need to agree to disagree man_shrugging.

@iRhonin yeah sounds good ;)
