### ISSUE TITLE
Participant's Names not Showing in Need Page

### ISSUE THREAD

**Issue by iRhonin** [SAY-DAO/frontend#9]
For example check this need: https://beta.sayapp.company/child/114/needs/7189

![image](https://user-images.githubusercontent.com/13151232/170886868-b46a9351-9902-44b0-881f-53b9b20f8c51.png)

**Comment by ehsan-g** [comment]
That was actually intentional. User who have paid can see their role and paid amount to verify their payments, however, they might not like others to find out how much they have paid for a child. If you think we should go back to previous version we can have a talk about it. @iRhonin
